name: The View from up Here
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7741935
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: The View from up Here
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c110b'
    - '#f1af58'
    - '#f5e6e9'
    - '#a1461a'
    - '#bb7a5a'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
